### ISSUE TITLE
ava_train_v2.2_with_fair_0.9.pkl

### ISSUE THREAD

**Issue by pokameng** [Siyu-C/ACAR-Net#10]
hello!
I want to konw the mean of 'time','midframe' in ava_train_v2.2_with_fair_0.9.pkl,so can you explain for me ?

**Comment by Siyu-C** [comment]
Hi @pokameng , 'time' is the timestamp of the key frame, which also appears in official AVA annotation files. On the other hand, 'midframe' is the index of the key frame in the extracted frames. Note that this index, as well as 'start_frame' and 'n_frames', are computed assuming frames are extracted with fps set to 30.

**Comment by pokameng** [comment]
OK，thanks，a lot！！！



---Original---
From: "Siyu ***@***.***&gt;
Date: Mon, Jun 28, 2021 23:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Siyu-C/ACAR-Net] ava_train_v2.2_with_fair_0.9.pkl (#10)




 
Hi @pokameng , 'time' is the timestamp of the key frame, which also appears in official AVA annotation files. On the other hand, 'midframe' is the index of the key frame in the extracted frames. Note that this index, as well as 'start_frame' and 'n_frames', are computed assuming frames are extracted with fps set to 30.

**Comment by pokameng** [comment]
@Siyu-C hello, by the way,the boundingbox in ava is decimal,but the sth-sth-v2 is integer,how to convert sth-sth-v2 to ava format?

**Comment by pokameng** [comment]
@Siyu-C hello,i have handled the sth-sth format,But i want to know wheather you will release the dataset UCF101 ?

**Comment by Siyu-C** [comment]
Hi @pokameng , currently we have no plan for releasing UCF101-24 models or configurations.

**Comment by yan-ctrl** [comment]
> Hi @pokameng , 'time' is the timestamp of the key frame, which also appears in official AVA annotation files. On the other hand, 'midframe' is the index of the key frame in the extracted frames. Note that this index, as well as 'start_frame' and 'n_frames', are computed assuming frames are extracted with fps set to 30.

I also want to know the meaning of label in the file. How did you get it? I compared the action label of AVA data set, but it doesn't correspond to lael of pkl file. I guess it is an action label, but it is different from that of AVA data set. Can you tell me?

**Comment by yan-ctrl** [comment]
> hello! I want to konw the mean of 'time','midframe' in ava_train_v2.2_with_fair_0.9.pkl,so can you explain for me ?

Hello, have you reproduced this article? Do you know the meaning of label in the file? I compared it with AVA data set and found that it is not the same as the action label of AVA data set. I am confused now.
