### ISSUE TITLE
How to evaluate ?

### ISSUE THREAD

**Issue by pokameng** [Siyu-C/ACAR-Net#14]
I want to evaluate testdataset by used my trained model,by it seemed run very slowly.Can  you  give me an example about evaluating ?Thanks!!!
@Siyu-C @junting

**Comment by Siyu-C** [comment]
It is likely that the data loading part is slow. Perhaps check data time.

**Comment by pokameng** [comment]
How to test? Because my test.pkl does not contains boundingbox.I check you eval.yaml,and i find that your pkl has boudingbox.So,i need to generate box by nyself,right?
@Siyu-C

**Comment by pokameng** [comment]
By the way ,Does the ACAR generate the boudingbox?Onlf i provide the original box,the ACAR can generate the predict box?

**Comment by Siyu-C** [comment]
Hi @pokameng , ACAR do not account for bounding box generation. An off-the-shelf detector is needed for building the dataset meta file.
