### ISSUE TITLE
are ACFB  features updated during training?

### ISSUE THREAD

**Issue by IoannaNti** [Siyu-C/ACAR-Net#15]
Hi, 

Are you updating ACFB  features during training?  From the paper I can see that the feature bank (ACFB) is initially filled with features from a trained ACAR-Net and that these features are used as key-values in the attention module. However, I am not sure if these memory features are further updated.

Thanks!

**Comment by Siyu-C** [comment]
Hi @IoannaNti , in our method we do not update these memory features. We simple use the trained ACAR-Net to extract both training and validation/testing banks.
