### ISSUE TITLE
What was the settings for your experiments

### ISSUE THREAD

**Issue by wjhmike95** [Siyu-C/ACAR-Net#16]
Thanks for your great job. In paper, you mentioned you set batch size as 32. However, you set batch size as 1 in config file, and set 8 gpus as default. The total batch size are 8 which is different from paper. Could you share the settings of experiments in your paper?  Thank you

**Comment by Siyu-C** [comment]
Hi @wjhmike95 , the default value 8 is meant to be the number of gpus on one single machine. In our original experiments in the paper, we use 4 nodes for training, hence the total batch size would be 32.

**Comment by wjhmike95** [comment]
Thank you for your explanation! I get one more question. Will you release the ResNet101 pretrain model?

**Comment by Siyu-C** [comment]
> > Hi @wjhmike95 , the default value 8 is meant to be the number of gpus on one single machine. In our original experiments in the paper, we use 4 nodes for training, hence the total batch size would be 32.
> 
> Thanks, btw Do experiments on ucf101-24 also take 32 as batch size?

Yes, we also set batch size to 32 for experiments on UCF101-24.
