### ISSUE TITLE
When will slowfast_resnet101 pretrain model be released

### ISSUE THREAD

**Issue by wjhmike95** [Siyu-C/ACAR-Net#17]
Great job @junting @Siyu-C. I wanna try a deeper backbone. Could you tell when will you release pretrained slowfast_resnet101 model? Thanks

**Comment by Siyu-C** [comment]
The SlowFast R-101 model pre-trained on AVA has been released. Another one pre-trained on AVA-Kinetics should be released shortly.

**Comment by wjhmike95** [comment]
> The SlowFast R-101 model pre-trained on AVA has been released. Another one pre-trained on AVA-Kinetics should be released shortly.

Sorry, I mean  the SlowFast R-101 pretrained on kinetics

**Comment by Siyu-C** [comment]
> > The SlowFast R-101 model pre-trained on AVA has been released. Another one pre-trained on AVA-Kinetics should be released shortly.
> 
> Sorry, I mean the SlowFast R-101 pretrained on kinetics

I see. Updated.

**Comment by gurkirt** [comment]
@junting  @Siyu-C  Thank you for making this code available, and well done, look much less hairy than pySlowfast. 
I can not find  SlowFast R-101 pretrained on kinetics-700, where is it?

**Comment by gurkirt** [comment]
Never mind, found it. Thanks

**Comment by jiaozizhao** [comment]
> Never mind, found it. Thanks

Hi, gurkirt,
May I know where did you find the model SlowFast R-101 pretrained on kinetics-700? Thanks a lot.
