### ISSUE TITLE
The mAP is different

### ISSUE THREAD

**Issue by pokameng** [Siyu-C/ACAR-Net#19]
Hello
@Siyu-C @junting 
Thanks for your great work!
I have a question when I run this code:
When I set batch size=8 and gpu =2 ,the mAP is very low,but batch size=1,gpu=1,the mAP is very high.So Can you tell me why?I do not konw how to explain this problem.

**Comment by Siyu-C** [comment]
Hi @pokameng , not sure whether you are running training or evaluation.
