### ISSUE TITLE
hi,about bbox

### ISSUE THREAD

**Issue by jun0wanan** [Siyu-C/ACAR-Net#7]
请问 clip和clip之间的bbox是怎么连接起来的？我看代码是一开始就roialign了，就是bbox是所有clip的feat亚，好像不是按照每个clip几个bbox的模式？

**Comment by jun0wanan** [comment]
> _No description provided._

**Comment by Siyu-C** [comment]
Hi @jun0wanan . I am not sure what exactly you are asking, but our pipeline adopts the simple way proposed by previous work, which only detects bboxes on the key frame of a clip, and duplicate the detected bboxes to other frames of the same clip. Note that the timestamp of the key frame is given by the dataset. Our current implementation directly reads bboxes from the annotation file. The bboxes can be either ground-truth or pre-computed by an off-the-shelf person detector.
